global:


templates:
  - '/etc/alertmanager/template/*.tmpl'


route:
  # Alerts notification are grouped accordingly to a hierarchy of labels.
  group_by: ['alertname']

  # How long to initially wait to send a notification for a group
  # of alerts. Allows to wait for an inhibiting alert to arrive or collect
  # more initial alerts for the same group. (Usually ~0s to few minutes.)
  group_wait: 30s

  # How long to wait before sending a notification about new alerts that
  # are added to a group of alerts for which an initial notification has
  # already been sent. (Usually ~5m or more.)
  group_interval: 5m

  # How long to wait before sending a notification again if it has already
  # been sent successfully for an alert. (Usually ~3h or more).
  repeat_interval: 1h
  receiver: 'slack'


receivers:
  - name: 'slack'


# Inhibition rules allow to mute a set of alerts given that another alert is firing.
inhibit_rules: